#!/usr/bin/env python3

import rospy
from std_msgs.msg import Float32MultiArray
import subprocess

# Set to keep track of vocalized numbers
vocalized_numbers = set()

def id_callback(data):
    global vocalized_numbers

    # Check if the ID is detected (non-zero positive value)
    aruco_id = data.data
    last_number = aruco_id[-1] if aruco_id else None

    if last_number >= 0:
        if last_number not in vocalized_numbers:
            # Log the numeric data received
            rospy.loginfo("Received numeric data: %d", last_number)
            
            # Use eSpeak to synthesize the speech
            try:
                subprocess.run(['espeak', f'The number detected is {last_number}'], check=True)
                # Add the number to the set of vocalized numbers
                vocalized_numbers.add(last_number)
            except subprocess.CalledProcessError as e:
                rospy.logerr(f"Error running eSpeak: {e}")
        else:
            rospy.loginfo("Number %d has already been vocalized.", last_number)


def main():
    rospy.init_node('espeak_subscriber', anonymous=True)
    rospy.Subscriber('/aruco_corners', Float32MultiArray, id_callback)
    rospy.loginfo('espeak activated')
    rospy.spin()

if __name__ == '__main__':
    main()
