#!/usr/bin/env python3

import math

import rospy
import tf2_ros
from std_msgs.msg import Time
from geometry_msgs.msg import TransformStamped

# Use this to broadcoast pose estimation
class Tf2BroadcasterTarget:
    def __init__(self, camera_name="camera", target_name="target"):
        self.camera_name = camera_name
        self.target_name = target_name
        
        rospy.loginfo("tf2_broadcaster_target sending target found...")

        # Setup tf2 broadcaster and timestamp publisher
        self.tfbr = tf2_ros.TransformBroadcaster()
        self.pub_found = rospy.Publisher('/emulated_uav/target_found', Time, queue_size=10)

    def send_tf_target(self, estimate_x=-0.4, estimate_y=0.2, estimate_z=1.35):
        # Generate our "found" timestamp
        time_found = rospy.Time.now()

        # Create a transform arbitrarily in the camera frame
        t = TransformStamped()
        t.header.stamp = time_found
        t.header.frame_id = self.camera_name
        t.child_frame_id = self.target_name
        
        t.transform.translation.x = estimate_x
        t.transform.translation.y = estimate_y
        t.transform.translation.z = estimate_z  # - altitude of the UAV camera Z.
        t.transform.rotation.x = 0.0
        t.transform.rotation.y = 0.0
        t.transform.rotation.z = 0.0
        t.transform.rotation.w = 1.0

        # Send the transformation to TF and publish the "found" timestamp
        self.tfbr.sendTransform(t)
        self.pub_found.publish(time_found)
        rospy.loginfo(f'tf2_broadcaster_target sent TF: {t.transform.translation} and timestamp: {time_found}')


if __name__ == '__main__':
	rospy.init_node('tf2_broadcaster_target')
	rospy.loginfo("tf2_broadcaster_target sending target found...")

	tf2broadcaster = Tf2BroadcasterTarget()

	# Give the nodes a few seconds to configure
	rospy.sleep(rospy.Duration(2))

	# Send out our target messages
	tf2broadcaster.send_tf_target()

	# Give the nodes a few seconds to transmit data
	# then we can exit
	rospy.sleep(rospy.Duration(2))
	rospy.loginfo("tf2_broadcaster_target sent TF and timestamp")